const http = require('http');

const API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1N2FhMTMyNS1mODM2LTRmOGItYTk2NC02NDA4NjJlMTQxZjYiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiNzNlMmRjMTgtMzU5MS00ZjljLWIyYjYtMzZhZjdlNjYwYzViIiwiaWF0IjoxNzc4Mjk1NDUxLCJleHAiOjE3ODA4MTU2MDB9.X7T72Ph9Hv1qY_I8bGB2KnFtmdJ18wVdk6rDiwSjJ9U';
const WF_ID = 'riCozLIp9vwM1mjt';

function req(method, path, body) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const r = http.request({
      hostname: 'localhost', port: 5678, path, method,
      headers: { 'X-N8N-API-KEY': API_KEY, 'Content-Type': 'application/json', ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {}) }
    }, res => { const c = []; res.on('data', d => c.push(d)); res.on('end', () => resolve(JSON.parse(c.join('')))); });
    r.on('error', reject); if (data) r.write(data); r.end();
  });
}

const $ = String.fromCharCode(36);

// Parse & Route: Hybrid classification (keyword rules + Ollama confirmation) + code-based field extraction
const PARSE_ROUTE_CODE = [
  `const ollamaData = ${$}input.first().json;`,
  `const prevData = ${$}('Validation Gate').first().json;`,
  `const doc = { ...prevData.doc };`,
  `doc.flags = Array.isArray(doc.flags) ? [...doc.flags] : [];`,
  ``,
  `try {`,
  `  const extracted = ${$}('Extract Text').first().json;`,
  `  if (extracted && extracted.doc) {`,
  `    doc.document_text = extracted.doc.document_text || doc.document_text;`,
  `    doc.flags = [...new Set([...doc.flags, ...(extracted.doc.flags || [])])];`,
  `  }`,
  `} catch(e) {}`,
  ``,
  `const rawText = doc.document_text || '';`,
  `const searchText = (rawText + ' ' + (doc.file_name || '') + ' ' + (doc.subject || '') + ' ' + (doc.sender || '')).toLowerCase();`,
  ``,
  `const VALID_LABELS = ['invoice','contract','intake_form','referral','receipt','court_document','id_document','tax_document','real_estate','correspondence','unknown'];`,
  `const ROUTING_MAP = { invoice:'accounts_payable', contract:'legal_review', intake_form:'client_services', referral:'patient_intake', receipt:'expense_management', court_document:'legal_urgent', id_document:'compliance', tax_document:'finance_team', real_estate:'transactions', correspondence:'general_inbox', unknown:'human_review_queue' };`,
  ``,
  `// ── Step 1: Keyword-based classification (deterministic, instant) ──────`,
  `function keywordClassify(t) {`,
  `  if (/\\b(invoice|inv-|amount due|bill to|invoice number|vendor invoice|billed by|remittance|payable to)\\b/.test(t)) return 'invoice';`,
  `  if (/\\b(patient referral|referring physician|npi:|diagnosis code|diagnosis:|referral to|authorization number|auth-)\\b/.test(t)) return 'referral';`,
  `  if (/\\b(non-disclosure|nda\\b|this agreement|shall not disclose|confidential information|governing law|party a|party b)\\b/.test(t)) return 'contract';`,
  `  if (/\\b(receipt|total paid|merchant:|transaction date|payment method:|purchase receipt)\\b/.test(t)) return 'receipt';`,
  `  if (/\\b(intake form|client intake|patient intake|service requested:|reason for visit|chief complaint)\\b/.test(t)) return 'intake_form';`,
  `  if (/\\b(case no|case number|plaintiff|defendant|in the court|motion for|order of|judicial)\\b/.test(t)) return 'court_document';`,
  `  if (/\\b(passport|driver.?s license|state id|license no|document no|date of expiry|issuing authority)\\b/.test(t)) return 'id_document';`,
  `  if (/\\b(w-?2\\b|1099-|form 1040|tax return|taxable income|tax year|irs|wages and tips)\\b/.test(t)) return 'tax_document';`,
  `  if (/\\b(purchase agreement|real estate|escrow|closing date|property address|buyer:|seller:|title insurance)\\b/.test(t)) return 'real_estate';`,
  `  if (/\\b(dear |to whom it may concern|sincerely,|memorandum|re: |per our discussion)\\b/.test(t)) return 'correspondence';`,
  `  return null;`,
  `}`,
  ``,
  `const kwLabel = keywordClassify(searchText);`,
  `const hintLabel = VALID_LABELS.includes((doc.document_class_hint || '').toLowerCase()) ? doc.document_class_hint.toLowerCase() : null;`,
  ``,
  `// ── Step 2: AI classification ──────────────────────────────────────────`,
  `const ollamaRaw = ollamaData.response || null;`,
  `let aiLabel = null, aiSuccess = false;`,
  ``,
  `try {`,
  `  if (!ollamaRaw || ollamaData.error) throw new Error('Ollama unavailable');`,
  `  const parsed = typeof ollamaRaw === 'string' ? JSON.parse(ollamaRaw) : ollamaRaw;`,
  `  const rawLabel = (parsed.classification_label || '').toLowerCase().trim().replace(/[^a-z_]/g, '');`,
  `  aiLabel = VALID_LABELS.includes(rawLabel) ? rawLabel : null;`,
  `  doc.ai_model_used = 'llama3.2';`,
  `  doc.ai_model_source = 'ollama_local';`,
  `  doc.ai_fallback_used = false;`,
  `  aiSuccess = true;`,
  `} catch(e) {`,
  `  doc.ai_model_used = null;`,
  `  doc.ai_model_source = 'fallback';`,
  `  doc.ai_fallback_used = true;`,
  `  doc.flags.push('ai_fallback_triggered');`,
  `}`,
  ``,
  `// ── Step 3: Consensus confidence scoring ──────────────────────────────`,
  `// Keywords are deterministic and trusted. AI is a second opinion.`,
  `// Agreement = high confidence. Keyword only = moderate. AI only = low.`,
  `let label, confidence;`,
  ``,
  `if (kwLabel && aiLabel && kwLabel === aiLabel) {`,
  `  label = kwLabel; confidence = 0.92;  // full consensus`,
  `  doc.flags.push('consensus_high_confidence');`,
  `} else if (kwLabel && aiLabel && kwLabel !== aiLabel) {`,
  `  label = kwLabel; confidence = 0.65;  // keyword wins, flag disagreement`,
  `  doc.flags.push('ai_keyword_disagreement');`,
  `} else if (kwLabel && !aiLabel) {`,
  `  label = kwLabel; confidence = 0.75;  // keyword only (AI unavailable or null)`,
  `  doc.flags.push('keyword_classification_only');`,
  `} else if (!kwLabel && aiLabel && aiLabel !== 'unknown') {`,
  `  label = aiLabel; confidence = 0.55;  // AI only, low confidence`,
  `  doc.flags.push('ai_classification_only');`,
  `} else if (hintLabel) {`,
  `  label = hintLabel; confidence = 0.45;  // hint fallback`,
  `  doc.flags.push('hint_used');`,
  `} else {`,
  `  label = 'unknown'; confidence = 0;`,
  `  doc.flags.push('unclassified');`,
  `}`,
  ``,
  `// ── Step 4: Code-based field extraction ────────────────────────────────`,
  `function extract(pattern, src, group) {`,
  `  try { const m = (src || '').match(pattern); return m ? (m[group || 1] || '').trim() || null : null; } catch(e) { return null; }`,
  `}`,
  ``,
  `let extractedFields = {};`,
  ``,
  `if (label === 'invoice') {`,
  `  extractedFields = {`,
  `    invoice_number: extract(/(?:invoice\\s*(?:number|#|no\\.?)|INV[-#])\\s*([\\w-]+)/i, rawText),`,
  `    vendor_name: extract(/(?:^|\\n)([A-Z][A-Za-z\\s]+(?:LLC|Inc\\.?|Corp\\.?|Co\\.?|Ltd\\.?))\\s*\\n/m, rawText),`,
  `    invoice_date: extract(/(?:invoice date|date)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{2,4}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s+\\d{1,2},?\\s+\\d{4})/i, rawText),`,
  `    due_date: extract(/due\\s*(?:date|by|on)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{2,4}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s+\\d{1,2},?\\s+\\d{4})/i, rawText),`,
  `    total_amount: extract(/(?:total(?: due| amount)?|amount due|grand total|balance due)[:\\s]*\\$?([\\d,]+\\.\\d{2})/i, rawText),`,
  `    currency: extract(/\\b(USD|EUR|GBP|CAD|AUD)\\b/, rawText) || 'USD',`,
  `    payment_terms: extract(/payment terms[:\\s]+([\\w\\s]+?)(?:\\n|$)/i, rawText)`,
  `  };`,
  `} else if (label === 'referral') {`,
  `  extractedFields = {`,
  `    patient_name: extract(/patient\\s*(?:name)?[:\\s]+([A-Za-z]+\\s+[A-Za-z]+)/i, rawText),`,
  `    date_of_birth: extract(/(?:date of birth|dob)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{2,4})/i, rawText),`,
  `    referring_physician: extract(/referring\\s*(?:physician|doctor|provider)[:\\s]+(?:Dr\\.?\\s+)?([A-Za-z]+\\s+[A-Za-z]+(?:,\\s*M\\.?D\\.?)?)/i, rawText),`,
  `    npi: extract(/NPI[:\\s#]+([0-9]{10})/i, rawText),`,
  `    diagnosis_code: extract(/(?:ICD|diagnosis\\s*code)[:\\s]+([A-Z]\\d{2,3}(?:\\.\\d+)?)/i, rawText),`,
  `    diagnosis_description: extract(/(?:diagnosis|condition|impression)[:\\s]+([A-Za-z][\\w\\s,]+?)(?:\\n|$)/i, rawText),`,
  `    authorization_number: extract(/(?:auth(?:orization)?\\s*(?:number|#|no)[:\\s]+)([\\w-]+)/i, rawText),`,
  `    urgency: extract(/urgency[:\\s]+([\\w]+)/i, rawText) || 'routine'`,
  `  };`,
  `} else if (label === 'contract') {`,
  `  extractedFields = {`,
  `    contract_type: extract(/^(NON-DISCLOSURE AGREEMENT|NDA|SERVICE AGREEMENT|PURCHASE AGREEMENT|CONSULTING AGREEMENT|EMPLOYMENT AGREEMENT|PARTNERSHIP AGREEMENT)/im, rawText),`,
  `    effective_date: extract(/(?:effective|entered into|dated?)\\s+(?:as of\\s+)?([A-Za-z]+\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/i, rawText),`,
  `    governing_law: extract(/governing\\s*law[:\\s]+(?:laws? of the State of\\s+)?([A-Za-z]+)/i, rawText),`,
  `    term: extract(/(\\d+)\\s+years?\\s+(?:from|term|agreement)/i, rawText)`,
  `  };`,
  `} else if (label === 'receipt') {`,
  `  extractedFields = {`,
  `    merchant_name: extract(/^([A-Z][\\w\\s&]+)\\s*\\n/m, rawText),`,
  `    transaction_date: extract(/(?:date|transaction date)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/i, rawText),`,
  `    total_amount: extract(/(?:total|amount)[:\\s]*\\$?([\\d,]+\\.\\d{2})/i, rawText),`,
  `    currency: extract(/\\b(USD|EUR|GBP|CAD|AUD)\\b/, rawText) || 'USD',`,
  `    payment_method: extract(/(?:paid by|payment method|card type)[:\\s]+([\\w\\s]+?)(?:\\n|$)/i, rawText)`,
  `  };`,
  `} else if (label === 'court_document') {`,
  `  extractedFields = {`,
  `    case_number: extract(/(?:case\\s*(?:no|number|#))[:\\s]+([\\w-]+)/i, rawText),`,
  `    court_name: extract(/(?:in the|before the)?\\s*(\\w+ court[\\w\\s]*)(?:\\n|$)/i, rawText),`,
  `    filing_date: extract(/(?:filed|filing date)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/i, rawText),`,
  `    document_type: extract(/^(MOTION|ORDER|COMPLAINT|SUMMONS|JUDGMENT|NOTICE|PETITION|SUBPOENA)/im, rawText)`,
  `  };`,
  `} else if (label === 'tax_document') {`,
  `  extractedFields = {`,
  `    form_type: extract(/\\b(W-?2|1099-?[A-Z]*|1040|1065|1120|990)\\b/i, rawText),`,
  `    tax_year: extract(/(?:tax year|year)[:\\s]+(\\d{4})|\\b(20\\d{2})\\b/, rawText),`,
  `    taxpayer_name: extract(/(?:employee|taxpayer)[:\\s]+([A-Za-z]+\\s+[A-Za-z]+)/i, rawText)`,
  `  };`,
  `} else if (label === 'real_estate') {`,
  `  extractedFields = {`,
  `    property_address: extract(/(?:property address|premises|located at|property:)[:\\s]+([\\d][\\w\\s,\\.]+?)(?:\\n|$)/i, rawText),`,
  `    purchase_price: extract(/(?:purchase price|sale price|agreed price)[:\\s]*\\$?([\\d,]+(?:\\.\\d{2})?)/i, rawText),`,
  `    closing_date: extract(/(?:closing date|close of escrow)[:\\s]+([A-Za-z]+\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/i, rawText)`,
  `  };`,
  `} else if (label === 'id_document') {`,
  `  extractedFields = {`,
  `    id_type: extract(/\\b(PASSPORT|DRIVER.?S LICENSE|STATE ID|NATIONAL ID)\\b/i, rawText),`,
  `    id_number: extract(/(?:license no|id no|document no|number)[:\\s]+([A-Z0-9]+)/i, rawText),`,
  `    full_name: extract(/(?:name|holder)[:\\s]+([A-Za-z]+\\s+[A-Za-z]+)/i, rawText),`,
  `    expiry_date: extract(/(?:expiry|expires|valid through|valid until)[:\\s]+(\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/i, rawText)`,
  `  };`,
  `} else if (label === 'correspondence') {`,
  `  extractedFields = {`,
  `    document_date: extract(/^((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\.?\\s+\\d{1,2},?\\s+\\d{4}|\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})/im, rawText),`,
  `    subject: doc.subject || extract(/(?:re|subject)[:\\s]+([^\\n]+)/i, rawText)`,
  `  };`,
  `} else if (label === 'intake_form') {`,
  `  extractedFields = {`,
  `    client_name: extract(/(?:name|client name|patient name)[:\\s]+([A-Za-z]+\\s+[A-Za-z]+)/i, rawText),`,
  `    contact_email: extract(/([\\w.+-]+@[\\w-]+\\.[\\w.]+)/, rawText),`,
  `    contact_phone: extract(/(\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4})/, rawText),`,
  `    service_requested: extract(/(?:service requested|reason for visit)[:\\s]+([^\\n]+)/i, rawText)`,
  `  };`,
  `}`,
  ``,
  `// Remove null values from extracted fields`,
  `extractedFields = Object.fromEntries(Object.entries(extractedFields).filter(([k,v]) => v !== null && v !== undefined && v !== ''));`,
  ``,
  `// ── Step 5: Enforce confidence thresholds ─────────────────────────────`,
  `let downstreamAction, reviewRequired = false;`,
  `if (label === 'unknown' || confidence < 0.50) {`,
  `  downstreamAction = 'human_review'; reviewRequired = true; doc.flags.push('low_confidence_review');`,
  `} else if (confidence < 0.80) {`,
  `  downstreamAction = 'human_review'; reviewRequired = true; doc.flags.push('moderate_confidence_review');`,
  `} else {`,
  `  downstreamAction = 'auto_process';`,
  `}`,
  `if (label === 'court_document') { downstreamAction = 'escalate'; reviewRequired = true; doc.flags.push('auto_escalated_court_doc'); }`,
  ``,
  `const year = new Date().getFullYear();`,
  `const month = String(new Date().getMonth() + 1).padStart(2, '0');`,
  `const routingDestination = ROUTING_MAP[label] || 'human_review_queue';`,
  `const filingTarget = label !== 'unknown' ? label + '/' + year + '/' + month : 'unclassified/pending';`,
  ``,
  `doc.classification_label = label;`,
  `doc.confidence_score = confidence;`,
  `doc.routing_destination = routingDestination;`,
  `doc.filing_target = filingTarget;`,
  `doc.downstream_action = downstreamAction;`,
  `doc.review_required = reviewRequired;`,
  `doc.extracted_fields = extractedFields;`,
  `doc.classification_result = { label, confidence, routing_destination: routingDestination, filing_target: filingTarget, keyword_match: kwLabel, ai_label: aiLabel, ai_success: aiSuccess };`,
  `doc.processed_at = new Date().toISOString();`,
  ``,
  `return [{ json: { doc, raw_payload: prevData.raw_payload } }];`
].join('\n');

async function main() {
  console.log('Fetching workflow...');
  const wf = await req('GET', `/api/v1/workflows/${WF_ID}`);

  const parseNode = wf.nodes.find(n => n.name === 'Parse & Route');
  parseNode.parameters.jsCode = PARSE_ROUTE_CODE;
  console.log('Updated Parse & Route with hybrid keyword + AI classification.');

  const payload = {
    name: wf.name, nodes: wf.nodes, connections: wf.connections,
    settings: { executionOrder: wf.settings.executionOrder, saveManualExecutions: wf.settings.saveManualExecutions },
    staticData: wf.staticData
  };

  const result = await req('PUT', `/api/v1/workflows/${WF_ID}`, payload);
  console.log(result.id ? 'Updated: ' + result.id : 'Error: ' + JSON.stringify(result).substring(0, 300));

  const active = await req('POST', `/api/v1/workflows/${WF_ID}/activate`);
  console.log('active:', active.active);
}

main().catch(console.error);
