// Convenience setup run by the `pretest` npm hook, so `pnpm test` "just works"
// locally with no manual steps (issue #23 follow-up).
//
// It (1) writes a gitignored `.env.test.local` pointing at the local pgvector test DB
// if it doesn't exist, and (2) best-effort starts that container via docker compose.
//
// It NEVER fails the test run: any problem (Docker down, etc.) is a warning, and the
// integration tests then surface the real connection error themselves. CI is skipped
// entirely — CI sets its own DATABASE_URL and provisions its own pgvector service, and
// runs `vitest` directly rather than `pnpm test`.

import { execFileSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ENV_FILE = resolve(process.cwd(), ".env.test.local");
const DB_URL = "postgresql://qad_user:testpassword@127.0.0.1:5544/qad_test";

// CI (and anyone who already exports DATABASE_URL) provides the DB — do nothing.
if (process.env.CI || process.env.DATABASE_URL) {
  process.exit(0);
}

// 1. Ensure .env.test.local exists so vitest.config.ts picks up DATABASE_URL.
//    Only written when missing, so a developer's custom value is never clobbered.
if (!existsSync(ENV_FILE)) {
  writeFileSync(
    ENV_FILE,
    [
      "# Auto-generated by scripts/ensure-test-db.mjs (gitignored — never commit).",
      "# Points the Vitest integration suite at the local pgvector test DB on :5544.",
      `DATABASE_URL=${DB_URL}`,
      "",
    ].join("\n"),
  );
  console.info("[test-db] wrote .env.test.local");
}

// 2. Best-effort: bring the pgvector container up and wait for it to be healthy.
//    `--wait` blocks on the healthcheck defined in docker-compose.yml, so the suite
//    never races a still-starting database. Returns fast when already running.
try {
  execFileSync(
    "docker",
    ["compose", "--profile", "test", "up", "-d", "--wait", "qad-test-db"],
    { stdio: "ignore" },
  );
  console.info("[test-db] qad-test-db is up on :5544");
} catch {
  console.warn(
    "[test-db] could not start qad-test-db — is Docker running? " +
      "Unit tests still run; integration tests will fail until the DB is up " +
      "(`docker compose --profile test up -d qad-test-db`).",
  );
}
