-- M3 (#26): atomic re-ingestion RPC + documents.error_detail.
--
-- The background ingestion worker (src/lib/ingestion/ingest-document.ts) drives
-- parse → chunk → embed → persist → status, per CLAUDE.md "Document Ingestion
-- Pipeline". Two schema pieces it depends on land here:
--
--   1. documents.error_detail — a durable failure reason, set alongside
--      status='error', so the M7 owner admin dashboard can show *why* a document
--      failed without re-deriving it from logs (which are M9 and ephemeral).
--
--   2. public.reingest_document_chunks(...) — the persist step, run as ONE
--      transaction so re-ingestion is atomic (locked decision D1, docs/m3-plan.md).
--
-- WHY AN RPC (decision D1 — single transaction).
-- Re-ingestion is "delete ALL old chunks+embeddings for the document_id, then
-- insert the new set". CLAUDE.md ("Re-ingestion on document update") requires the
-- old vectors be gone before the new ones land, or stale chunks leak into
-- retrieval. D1 hardens that: the delete + insert must be ONE transaction, so a
-- mid-failure rolls back to the prior good state — a document is never left
-- half-wiped (old chunks deleted, new insert failed → zero chunks, silently
-- broken retrieval). The worker flips status to 'ready' only after this function
-- COMMITS; any failure raises, the transaction rolls back with the old rows
-- intact, and the worker records status='error' + error_detail.
--
-- supabase-js cannot run a multi-statement transaction over PostgREST (each
-- .from().insert()/.delete() is its own round-trip / autocommit), so D1 is
-- implemented as this plpgsql function: a function body is one implicit
-- transaction, so the delete and both inserts either all commit or all roll back.
-- This also makes first-ingest and re-ingest the SAME path — on first ingest the
-- delete simply matches zero rows.
--
-- embeddings are NOT deleted explicitly: embeddings_chunk_tenant_fk is
-- ON DELETE CASCADE (20260618000003), so deleting a chunk drops its embedding.
--
-- p_chunks PAYLOAD SHAPE — a JSON array, one element per chunk, each:
--   {
--     "id":          "<uuid>",      -- chunk id, generated by the caller
--     "chunk_text":  "<text>",
--     "chunk_index": <int>,         -- 0-based, unique within the document
--     "token_count": <int>,
--     "embedding":   "[f1,f2,...]"  -- pgvector text literal, 768 dims
--   }
-- The caller (chunkAndEmbed) generates the chunk ids so it can pair each chunk
-- with its embedding in the same payload element; both rows are inserted here
-- from that one id. Returns the number of chunk rows inserted.

alter table public.documents
  add column error_detail text;

comment on column public.documents.error_detail is
  'Failure reason recorded by the ingestion worker when status = ''error'' '
  '(NULL otherwise). Durable so the M7 admin dashboard can surface why a '
  'document failed without re-deriving it from logs.';

-- ---------------------------------------------------------------------------
-- reingest_document_chunks — atomic replace of a document's chunks + embeddings.
--
-- security invoker (the default, stated explicitly): the only caller is the
-- ingestion worker via the service_role client, which already bypasses RLS and
-- holds the table privileges. Running with the invoker's rights — not definer —
-- means this function grants no extra authority of its own; the execute grant
-- below is the single gate, and it is service_role-only.
--
-- set search_path = '' so the function does not depend on the caller's
-- search_path (Supabase linter: function_search_path_mutable). Every reference is
-- schema-qualified (public.*, pg_catalog casts), so an empty search_path is safe.
-- ---------------------------------------------------------------------------

create or replace function public.reingest_document_chunks(
  p_document_id  uuid,
  p_tenant_id    uuid,
  p_chunks       jsonb,
  p_model_version text
) returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_inserted integer;
begin
  -- 1. Delete ALL existing chunks for this (document, tenant). Embeddings cascade
  --    via embeddings_chunk_tenant_fk (ON DELETE CASCADE). On first ingest this
  --    matches zero rows — the delete + insert is one path for both cases.
  delete from public.document_chunks
  where document_id = p_document_id
    and tenant_id   = p_tenant_id;

  -- 2. Insert the new chunk rows from the JSON payload. tenant_id is the trusted
  --    p_tenant_id argument (from the documents row), never a value embedded in
  --    p_chunks — matching the tenant-scoping convention used throughout ingestion.
  insert into public.document_chunks (id, document_id, tenant_id, chunk_text, chunk_index, token_count)
  select
    (c->>'id')::uuid,
    p_document_id,
    p_tenant_id,
    c->>'chunk_text',
    (c->>'chunk_index')::integer,
    (c->>'token_count')::integer
  from jsonb_array_elements(p_chunks) as c;

  get diagnostics v_inserted = row_count;

  -- 3. Insert one embedding per chunk, keyed by the same id from the same payload
  --    element, so a chunk and its vector can never be mispaired.
  insert into public.embeddings (chunk_id, tenant_id, embedding, model_version)
  select
    (c->>'id')::uuid,
    p_tenant_id,
    -- public.vector, not bare ::vector: search_path is '' (see above), and the
    -- pgvector type lives in the public schema (create extension ... in 20260618000003),
    -- so the cast must be schema-qualified or it fails with "type vector does not exist".
    (c->>'embedding')::public.vector,
    p_model_version
  from jsonb_array_elements(p_chunks) as c;

  -- Whole body is one implicit transaction (D1): if either insert violates a
  -- constraint (duplicate chunk_index, wrong-dim vector, mismatched tenant FK,
  -- ...) the exception propagates, the delete above rolls back too, and the
  -- document's prior chunks/embeddings are left untouched.
  return v_inserted;
end;
$$;

comment on function public.reingest_document_chunks(uuid, uuid, jsonb, text) is
  'Atomically replace a document''s chunks + embeddings (delete all, then insert '
  'the payload set) in one transaction — locked decision D1. Caller scopes to '
  'p_tenant_id; service_role-only.';

-- ---------------------------------------------------------------------------
-- Grants: service_role is the only ingestion write path (it already holds the
-- underlying table privileges and bypasses RLS). Revoke from everyone else first
-- so the function is never callable by a tenant-facing client — same posture as
-- custom_access_token_hook (20260616000001).
-- ---------------------------------------------------------------------------

revoke all on function public.reingest_document_chunks(uuid, uuid, jsonb, text)
  from public, anon, authenticated;

grant execute on function public.reingest_document_chunks(uuid, uuid, jsonb, text)
  to service_role;
